"""
validate_data.py

This script validates the healthcare CSV files generated by
generate_sample_data.py.

Files checked:
    - patients.csv
    - providers.csv
    - appointments.csv
    - payments.csv

Validation checks:
    1. Required columns
    2. Null primary keys
    3. Duplicate IDs
    4. Invalid appointment statuses
    5. Negative payment amounts
    6. Appointment referencing nonexistent patient
    7. Payment referencing nonexistent appointment
    8. Invalid dates
    9. Billed/paid/outstanding inconsistencies

The raw data is NOT modified.

A validation report is generated in:
    data/processed/validation_report.csv
"""

from pathlib import Path

import pandas as pd


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

RAW_DIR = BASE_DIR / "data" / "raw"

PROCESSED_DIR = BASE_DIR / "data" / "processed"

VALIDATION_REPORT = (
    PROCESSED_DIR / "validation_report.csv"
)


# ============================================================
# EXPECTED COLUMNS
# ============================================================

REQUIRED_COLUMNS = {

    "patients.csv": [
        "patient_id",
        "first_name",
        "last_name",
        "date_of_birth",
        "gender",
        "phone",
        "email",
        "city",
        "state",
        "registration_date",
        "insurance_provider",
        "insurance_id",
        "patient_status",
    ],

    "providers.csv": [
        "provider_id",
        "first_name",
        "last_name",
        "specialization",
        "department",
        "license_number",
        "phone",
        "email",
        "hospital_name",
        "city",
        "state",
        "years_of_experience",
        "provider_status",
    ],

    "appointments.csv": [
        "appointment_id",
        "patient_id",
        "provider_id",
        "appointment_date",
        "appointment_time",
        "appointment_type",
        "appointment_status",
        "reason",
        "diagnosis",
        "notes",
        "created_at",
    ],

    "payments.csv": [
        "payment_id",
        "appointment_id",
        "patient_id",
        "payment_date",
        "amount",
        "payment_method",
        "insurance_amount",
        "patient_amount",
        "payment_status",
        "transaction_id",
        "currency",
    ],
}


# ============================================================
# PRIMARY KEYS
# ============================================================

PRIMARY_KEYS = {

    "patients.csv": "patient_id",

    "providers.csv": "provider_id",

    "appointments.csv": "appointment_id",

    "payments.csv": "payment_id",
}


# ============================================================
# VALID APPOINTMENT STATUSES
# ============================================================

VALID_APPOINTMENT_STATUSES = {
    "Completed",
    "Scheduled",
    "Cancelled",
    "No Show",
}


# ============================================================
# VALID PAYMENT STATUSES
# ============================================================

VALID_PAYMENT_STATUSES = {
    "Paid",
    "Pending",
    "Failed",
}


# ============================================================
# STORE VALIDATION ERRORS
# ============================================================

validation_errors = []


def add_error(
    file_name,
    check_name,
    row_number,
    column_name,
    value,
    message,
):
    """
    Add one validation error to the report.
    """

    validation_errors.append(
        {
            "file": file_name,
            "check": check_name,
            "row": row_number,
            "column": column_name,
            "value": value,
            "message": message,
        }
    )


# ============================================================
# LOAD DATA
# ============================================================

def load_data():

    print("=" * 70)
    print("LOADING DATA")
    print("=" * 70)

    data = {}

    files = [
        "patients.csv",
        "providers.csv",
        "appointments.csv",
        "payments.csv",
    ]

    for file_name in files:

        file_path = RAW_DIR / file_name

        if not file_path.exists():

            print(
                f"ERROR: {file_name} not found at {file_path}"
            )

            continue

        try:

            df = pd.read_csv(file_path)

            data[file_name] = df

            print(
                f"{file_name}: {len(df)} records loaded"
            )

        except Exception as error:

            print(
                f"ERROR reading {file_name}: {error}"
            )

    print()

    return data


# ============================================================
# CHECK 1: REQUIRED COLUMNS
# ============================================================

def check_required_columns(data):

    print("Checking required columns...")

    for file_name, required_columns in REQUIRED_COLUMNS.items():

        if file_name not in data:
            continue

        df = data[file_name]

        actual_columns = set(df.columns)

        for column in required_columns:

            if column not in actual_columns:

                add_error(
                    file_name=file_name,
                    check_name="required_columns",
                    row_number="N/A",
                    column_name=column,
                    value="MISSING",
                    message=(
                        f"Required column '{column}' "
                        f"is missing."
                    ),
                )

                print(
                    f"  ERROR: {file_name} -> "
                    f"missing column '{column}'"
                )

    print()


# ============================================================
# CHECK 2: NULL PRIMARY KEYS
# ============================================================

def check_null_primary_keys(data):

    print("Checking null primary keys...")

    for file_name, primary_key in PRIMARY_KEYS.items():

        if file_name not in data:
            continue

        df = data[file_name]

        if primary_key not in df.columns:
            continue

        null_rows = df[
            df[primary_key].isna()
            | (df[primary_key].astype(str).str.strip() == "")
        ]

        for index, row in null_rows.iterrows():

            add_error(
                file_name=file_name,
                check_name="null_primary_key",
                row_number=index + 2,
                column_name=primary_key,
                value="NULL",
                message=(
                    f"Primary key '{primary_key}' "
                    f"cannot be null."
                ),
            )

        if len(null_rows) > 0:

            print(
                f"  ERROR: {file_name} -> "
                f"{len(null_rows)} null primary keys"
            )

    print()


# ============================================================
# CHECK 3: DUPLICATE IDS
# ============================================================

def check_duplicate_ids(data):

    print("Checking duplicate IDs...")

    for file_name, primary_key in PRIMARY_KEYS.items():

        if file_name not in data:
            continue

        df = data[file_name]

        if primary_key not in df.columns:
            continue

        duplicate_mask = (
            df[primary_key].duplicated(
                keep=False
            )
            & df[primary_key].notna()
        )

        duplicate_rows = df[duplicate_mask]

        for index, row in duplicate_rows.iterrows():

            duplicate_value = row[primary_key]

            add_error(
                file_name=file_name,
                check_name="duplicate_id",
                row_number=index + 2,
                column_name=primary_key,
                value=duplicate_value,
                message=(
                    f"Duplicate ID found: "
                    f"{duplicate_value}"
                ),
            )

        if len(duplicate_rows) > 0:

            print(
                f"  ERROR: {file_name} -> "
                f"{len(duplicate_rows)} rows "
                f"with duplicate IDs"
            )

    print()


# ============================================================
# CHECK 4: INVALID APPOINTMENT STATUSES
# ============================================================

def check_appointment_statuses(data):

    print("Checking appointment statuses...")

    file_name = "appointments.csv"

    if file_name not in data:
        return

    df = data[file_name]

    if "appointment_status" not in df.columns:
        return

    invalid_mask = ~df[
        "appointment_status"
    ].isin(VALID_APPOINTMENT_STATUSES)

    invalid_rows = df[invalid_mask]

    for index, row in invalid_rows.iterrows():

        status = row["appointment_status"]

        add_error(
            file_name=file_name,
            check_name="invalid_appointment_status",
            row_number=index + 2,
            column_name="appointment_status",
            value=status,
            message=(
                f"Invalid appointment status "
                f"'{status}'. "
                f"Allowed values: "
                f"{sorted(VALID_APPOINTMENT_STATUSES)}"
            ),
        )

    if len(invalid_rows) > 0:

        print(
            f"  ERROR: {len(invalid_rows)} "
            f"invalid appointment statuses"
        )

    print()


# ============================================================
# CHECK 5: NEGATIVE PAYMENT AMOUNTS
# ============================================================

def check_negative_payment_amounts(data):

    print("Checking negative payment amounts...")

    file_name = "payments.csv"

    if file_name not in data:
        return

    df = data[file_name]

    if "amount" not in df.columns:
        return

    numeric_amount = pd.to_numeric(
        df["amount"],
        errors="coerce"
    )

    negative_rows = df[
        numeric_amount < 0
    ]

    for index, row in negative_rows.iterrows():

        amount = row["amount"]

        add_error(
            file_name=file_name,
            check_name="negative_payment_amount",
            row_number=index + 2,
            column_name="amount",
            value=amount,
            message=(
                "Payment amount cannot be negative."
            ),
        )

    if len(negative_rows) > 0:

        print(
            f"  ERROR: {len(negative_rows)} "
            f"negative payment amounts"
        )

    print()


# ============================================================
# CHECK 6: APPOINTMENT -> PATIENT
# ============================================================

def check_appointment_patient_reference(data):

    print(
        "Checking appointment patient references..."
    )

    if "appointments.csv" not in data:
        return

    if "patients.csv" not in data:
        return

    appointments = data["appointments.csv"]

    patients = data["patients.csv"]

    if "patient_id" not in appointments.columns:
        return

    if "patient_id" not in patients.columns:
        return

    valid_patient_ids = set(
        patients["patient_id"]
        .dropna()
        .astype(str)
    )

    for index, row in appointments.iterrows():

        patient_id = str(
            row["patient_id"]
        )

        if patient_id not in valid_patient_ids:

            add_error(
                file_name="appointments.csv",
                check_name="invalid_patient_reference",
                row_number=index + 2,
                column_name="patient_id",
                value=patient_id,
                message=(
                    f"Appointment references "
                    f"nonexistent patient "
                    f"'{patient_id}'."
                ),
            )

    invalid_count = sum(
        1
        for error in validation_errors
        if error["check"]
        == "invalid_patient_reference"
    )

    if invalid_count > 0:

        print(
            f"  ERROR: {invalid_count} "
            f"appointments reference "
            f"nonexistent patients"
        )

    print()


# ============================================================
# CHECK 7: PAYMENT -> APPOINTMENT
# ============================================================

def check_payment_appointment_reference(data):

    print(
        "Checking payment appointment references..."
    )

    if "payments.csv" not in data:
        return

    if "appointments.csv" not in data:
        return

    payments = data["payments.csv"]

    appointments = data["appointments.csv"]

    if "appointment_id" not in payments.columns:
        return

    if "appointment_id" not in appointments.columns:
        return

    valid_appointment_ids = set(
        appointments["appointment_id"]
        .dropna()
        .astype(str)
    )

    for index, row in payments.iterrows():

        appointment_id = str(
            row["appointment_id"]
        )

        if appointment_id not in valid_appointment_ids:

            add_error(
                file_name="payments.csv",
                check_name="invalid_appointment_reference",
                row_number=index + 2,
                column_name="appointment_id",
                value=appointment_id,
                message=(
                    f"Payment references "
                    f"nonexistent appointment "
                    f"'{appointment_id}'."
                ),
            )

    invalid_count = sum(
        1
        for error in validation_errors
        if error["check"]
        == "invalid_appointment_reference"
    )

    if invalid_count > 0:

        print(
            f"  ERROR: {invalid_count} "
            f"payments reference "
            f"nonexistent appointments"
        )

    print()


# ============================================================
# CHECK 8: INVALID DATES
# ============================================================

def check_invalid_dates(data):

    print("Checking invalid dates...")

    date_columns = {

        "patients.csv": [
            "date_of_birth",
            "registration_date",
        ],

        "providers.csv": [],

        "appointments.csv": [
            "appointment_date",
            "created_at",
        ],

        "payments.csv": [
            "payment_date",
        ],
    }

    for file_name, columns in date_columns.items():

        if file_name not in data:
            continue

        df = data[file_name]

        for column in columns:

            if column not in df.columns:
                continue

            converted_dates = pd.to_datetime(
                df[column],
                errors="coerce"
            )

            invalid_mask = (
                converted_dates.isna()
                & df[column].notna()
                & (
                    df[column]
                    .astype(str)
                    .str.strip()
                    != ""
                )
            )

            invalid_rows = df[invalid_mask]

            for index, row in invalid_rows.iterrows():

                value = row[column]

                add_error(
                    file_name=file_name,
                    check_name="invalid_date",
                    row_number=index + 2,
                    column_name=column,
                    value=value,
                    message=(
                        f"Invalid date value "
                        f"'{value}'."
                    ),
                )

            if len(invalid_rows) > 0:

                print(
                    f"  ERROR: {file_name} -> "
                    f"{column}: "
                    f"{len(invalid_rows)} invalid dates"
                )

    print()


# ============================================================
# CHECK 9: BILLED / PAID / OUTSTANDING
# ============================================================

def check_billed_paid_outstanding(data):

    print(
        "Checking billed/paid/outstanding "
        "consistency..."
    )

    if "payments.csv" not in data:
        return

    payments = data["payments.csv"]

    required_columns = [
        "amount",
        "insurance_amount",
        "patient_amount",
        "payment_status",
    ]

    for column in required_columns:

        if column not in payments.columns:

            print(
                f"  WARNING: '{column}' column "
                f"not found in payments.csv"
            )

            return

    # Convert monetary columns to numbers
    amount = pd.to_numeric(
        payments["amount"],
        errors="coerce"
    )

    insurance_amount = pd.to_numeric(
        payments["insurance_amount"],
        errors="coerce"
    )

    patient_amount = pd.to_numeric(
        payments["patient_amount"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Check 9A:
    #
    # Billed amount should equal:
    #
    # insurance amount + patient amount
    #
    # Example:
    #
    # amount = 1500
    # insurance = 1200
    # patient = 300
    #
    # 1200 + 300 = 1500
    # --------------------------------------------------------

    calculated_total = (
        insurance_amount + patient_amount
    )

    inconsistent_split = (
        (amount - calculated_total).abs()
        > 0.01
    )

    for index in payments[
        inconsistent_split
    ].index:

        add_error(
            file_name="payments.csv",
            check_name="billed_paid_outstanding",
            row_number=index + 2,
            column_name="amount",
            value=amount.loc[index],
            message=(
                "Amount is inconsistent with "
                "insurance_amount + patient_amount."
            ),
        )

    # --------------------------------------------------------
    # Check 9B:
    #
    # Paid status should have a fully allocated amount.
    #
    # For Paid:
    #
    # insurance + patient = amount
    # outstanding = 0
    #
    # For Pending/Failed:
    # payment may not be fully paid.
    # --------------------------------------------------------

    paid_mask = (
        payments["payment_status"] == "Paid"
    )

    invalid_paid_rows = payments[
        paid_mask
        & (
            (amount - calculated_total).abs()
            > 0.01
        )
    ]

    for index in invalid_paid_rows.index:

        add_error(
            file_name="payments.csv",
            check_name="paid_amount_inconsistency",
            row_number=index + 2,
            column_name="payment_status",
            value="Paid",
            message=(
                "Payment is marked as Paid but "
                "billed amount does not match "
                "the allocated paid amounts."
            ),
        )

    # --------------------------------------------------------
    # Check 9C:
    #
    # Negative insurance/patient amounts
    # --------------------------------------------------------

    negative_insurance = payments[
        insurance_amount < 0
    ]

    for index in negative_insurance.index:

        add_error(
            file_name="payments.csv",
            check_name="negative_insurance_amount",
            row_number=index + 2,
            column_name="insurance_amount",
            value=insurance_amount.loc[index],
            message=(
                "Insurance amount cannot be negative."
            ),
        )

    negative_patient = payments[
        patient_amount < 0
    ]

    for index in negative_patient.index:

        add_error(
            file_name="payments.csv",
            check_name="negative_patient_amount",
            row_number=index + 2,
            column_name="patient_amount",
            value=patient_amount.loc[index],
            message=(
                "Patient amount cannot be negative."
            ),
        )

    # --------------------------------------------------------
    # Check 9D:
    #
    # Calculate outstanding amount.
    #
    # billed amount = amount
    #
    # paid amount =
    #     amount when payment is Paid
    #     0 otherwise
    #
    # outstanding =
    #     billed - paid
    #
    # This is calculated because the current
    # payments.csv schema does not contain a separate
    # outstanding_amount column.
    # --------------------------------------------------------

    calculated_paid = amount.where(
        payments["payment_status"] == "Paid",
        0
    )

    calculated_outstanding = (
        amount - calculated_paid
    )

    # Outstanding cannot be negative
    negative_outstanding = (
        calculated_outstanding < -0.01
    )

    for index in payments[
        negative_outstanding
    ].index:

        add_error(
            file_name="payments.csv",
            check_name="outstanding_amount",
            row_number=index + 2,
            column_name="amount",
            value=amount.loc[index],
            message=(
                "Outstanding amount cannot "
                "be negative."
            ),
        )

    total_errors = sum(
        1
        for error in validation_errors
        if error["check"]
        in {
            "billed_paid_outstanding",
            "paid_amount_inconsistency",
            "negative_insurance_amount",
            "negative_patient_amount",
            "outstanding_amount",
        }
    )

    if total_errors > 0:

        print(
            f"  ERROR: {total_errors} "
            f"financial inconsistencies found"
        )

    else:

        print(
            "  PASS: Billed/paid/outstanding "
            "amounts are consistent."
        )

    print()


# ============================================================
# GENERATE VALIDATION REPORT
# ============================================================

def generate_report():

    PROCESSED_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    if validation_errors:

        report_df = pd.DataFrame(
            validation_errors
        )

    else:

        report_df = pd.DataFrame(
            columns=[
                "file",
                "check",
                "row",
                "column",
                "value",
                "message",
            ]
        )

    report_df.to_csv(
        VALIDATION_REPORT,
        index=False
    )

    return report_df


# ============================================================
# PRINT SUMMARY
# ============================================================

def print_summary():

    print("=" * 70)
    print("VALIDATION SUMMARY")
    print("=" * 70)

    if not validation_errors:

        print("STATUS: PASS")
        print("No data quality errors found.")

    else:

        print("STATUS: FAIL")

        print(
            f"Total validation errors: "
            f"{len(validation_errors)}"
        )

        print()

        error_counts = {}

        for error in validation_errors:

            check = error["check"]

            error_counts[check] = (
                error_counts.get(check, 0) + 1
            )

        print("Errors by check:")

        for check, count in error_counts.items():

            print(
                f"  {check}: {count}"
            )

    print()

    print(
        f"Validation report: "
        f"{VALIDATION_REPORT}"
    )

    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print("=" * 70)
    print("HEALTHCARE DATA VALIDATION")
    print("=" * 70)
    print()

    # Load CSV files
    data = load_data()

    if not data:

        print(
            "ERROR: No input files were found."
        )

        return

    # --------------------------------------------------------
    # Run validation checks
    # --------------------------------------------------------

    check_required_columns(data)

    check_null_primary_keys(data)

    check_duplicate_ids(data)

    check_appointment_statuses(data)

    check_negative_payment_amounts(data)

    check_appointment_patient_reference(data)

    check_payment_appointment_reference(data)

    check_invalid_dates(data)

    check_billed_paid_outstanding(data)

    # --------------------------------------------------------
    # Generate report
    # --------------------------------------------------------

    generate_report()

    # --------------------------------------------------------
    # Print final summary
    # --------------------------------------------------------

    print_summary()


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()